# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'RxSwift学习' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for RxSwift学习
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSource'

end
